### PR TITLE
Fix elseIf UI showing `NaN` instead of a value.

### PR DESCRIPTION
**Pull request by keithclark**
# Description

This PR fixes an issue with the "else" count UI in the`if/else` variant of the if logic blocks. Adding a block and clicking`...` shows the UI for managing the block. In the screen grab below you can see that the `elseif` value is blank (it should be `0`):

Screen Shot 2020-01-29 at 22 36 30 :x: 

Clicking `+` or `-` triggers an update, which results in `NaN`:
Screen Shot 2020-01-29 at 22 36 38 :x: 

This update ensures that `controls_if_else_custom.elseIfs` is initialized to `0`, which fixes the problem:

Screen Shot 2020-01-29 at 22 43 52 ✅  

## Type of change

Bug fix (non-breaking change which fixes an issue)

## Source

Here's the source for creating app that shows the issue:

```js
{
  "source": "<xml xmlns=\"http://www.w3.org/1999/xhtml\"><block type=\"controls_if_else_custom\" id=\"|eI3i*DR~|q`}/2G_OUo\" x=\"454\" y=\"187\"><field name=\"CONFIG\">{\"else\":true,\"elseIfs\":null}</field></block></xml>",
  "code": "if (false) {\n} else {\n}\n",
  "parts": [],
  "profile": "default"
}
```

### CODE REVIEW

**Comment by TeamKano** [comment]
<table>
    <tr>
        <th colspan="3">Coverage summary</th>
    </tr>
<tr>
        <td>Statements</td>
        <td>29.4%</td>
        <td>2005/6820</td>
    </tr>
<tr>
        <td>Branches</td>
        <td>20.35%</td>
        <td>211/1037</td>
    </tr>
<tr>
        <td>Functions</td>
        <td>29.39%</td>
        <td>649/2208</td>
    </tr>
<tr>
        <td>Lines</td>
        <td>29.28%</td>
        <td>1938/6618</td>
    </tr>
</table>

*From Jenkins: kano-code/PR-1827*

**Comment by keithclark** [comment]
If you're looking for something else to justify a version bump, this is related to if/elseif/else blocks: https://github.com/KanoComponents/kwc-blockly/pull/70

**Comment by rachaelcodes** [comment]
Cool - both of those should now be in: @kano/code (3.0.1-alpha.25)

**Comment by keithclark** [comment]
Thanks @rachaelcodes 

Is there a way I tell which version is being served in production (a JS property or HTTP header etc.) ?

**Pull request merged**
