### PR TITLE
creator: Change file type of export to json

### PR DESCRIPTION
**Pull request by onishiweb**

### CODE REVIEW

**Review by joe-thom — APPROVED** [review]

**Review by tombettany — COMMENTED** [review]
Just a thought on this, if we want our users to be able to double click on a Kano share (KC, MA, anything else) and for it to be able to auto-launch the associated app then we basically have to have a designated extension for each app (even if the format underpinning them is actually JSON). If this is something that we don't care about doing then this is absolutely fine but just wanted to throw it out there.

**Comment by onishiweb** [comment]
> Just a thought on this, if we want our users to be able to double click on a Kano share (KC, MA, anything else) and for it to be able to auto-launch the associated app then we basically have to have a designated extension for each app (even if the format underpinning them is actually JSON). If this is something that we don't care about doing then this is absolutely fine but just wanted to throw it out there.

@tombettany This change is just for the challenge creator that uses `json`, it won't effect regular user exports of their own creations.

**Comment by tombettany** [comment]
Ah! Then ignore me.

**Comment by TeamKano** [comment]
<table>
    <tr>
        <th colspan="3">Coverage summary</th>
    </tr>
<tr>
        <td>Statements</td>
        <td>29.36%</td>
        <td>2003/6823</td>
    </tr>
<tr>
        <td>Branches</td>
        <td>20.23%</td>
        <td>212/1048</td>
    </tr>
<tr>
        <td>Functions</td>
        <td>29.39%</td>
        <td>650/2212</td>
    </tr>
<tr>
        <td>Lines</td>
        <td>29.23%</td>
        <td>1935/6620</td>
    </tr>
</table>

*From Jenkins: kano-code/PR-1856*

**Pull request merged**
